image: Ubuntu

stack: jdk 11

branches:
  only:
    - master

build: off

install:

  - java -jar ./artifacts/app-mbank.jar &

build_script:
  - name: Change wrapper permissions
      run: chmod +x ./gradlew
  - ./gradlew test --info