image: Ubuntu

stack: jdk 11

branches:
  only:
    - master

build: off
before_install:
  - chmod +x gradlew

install:

  - java -jar ./artifacts/app-mbank.jar &

build_script:
  - ./gradlew test --info